### ISSUE TITLE
Can use firebase for backend?

### ISSUE THREAD

**Issue by ublockme** [pensil-inc/flutter_pensil_app#1]
hey bro! Hope well, 
Can we use firestore for backend? 
if yes, can you guide me to change?
which one is best? Node,js or Firebase Firestore or firebase realtime?
Im going to work with this project source code to learn more.

**Comment by TheAlphamerc** [comment]
Yes, you can use firestore as a backend but it won't be that easy. First of all you need to understand its database architecture and then replace api gatway implementation with firestore service class. Doing so will consume much time as this project is tend to consume rest apis.

I suggest you to use Node.js in backend as it is scalable  and more secure than firebase.
Firebase query is very limited and you cant build simple search query like get all Strings contains a substring in DB. Its grows ugly as your business logic grow.

Node on other hand have an easy learning curve and allows you to construct your back end however you like. You can add DB driver in express JS to support any kind of DB you are more comfortable with.

**Comment by ublockme** [comment]
Thank u for ur information.
