### ISSUE TITLE
Setup heelp

### ISSUE THREAD

**Issue by ritam749** [pensil-inc/flutter_pensil_app#2]
I really like your app(hence want to improve upon it),could you please tell me how to setup this app along with the server side code to get this flutter app running, it would be very helpful

**Comment by TheAlphamerc** [comment]
Hello @ritam749 , If you look at readme.md file you can find setup instruction there.
Click [here](https://github.com/pensil-inc/flutter_pensil_app#project-setup) to check app setup instructions.
Click [here](https://github.com/pensil-inc/pensil-app-backend#project-setup) to check server setup instructions.
